<?php

//modulos del sistema se pueden agregar mas
define('USUARIOS','USUARIOS');
define('PRODUCTOS','PRODUCTOS');
define('PEDIDOS','PEDIDOS');
define('CLIENTES','CLIENTES');
define('SERVICIOS','SERVICIOS');
define('FACTURAS','FACTURAS');
define('REPORTES','RESPORTES');
define('NOTIFICACIONES','NOTIFICACIONES');
define('TELAS','TELAS');
define('MATERIALES','MATERIALES');
define('ARTICULOS','ACTICULOS');
define('ESTADISTICAS','ESTADISTICAS');
define('EXAMPLE_MODULE','EXAMPLE_MODULE');
define('INICIAR_SESION','INICIAR SESION');
define('CERRAR_SESION','CERRAR SESION');
define('BITACORA','BITACORA');
define('ROLES_PERMISOS','ROLES Y PERMISOS');
define('MODULOS','MODULOS');
define('LOGIN','LOGIN');
define('LOGOUT','LOGOUT');
